name: Merge Pull Request

on:
  pull_request_review:
    types: [submitted] 

permissions:
  contents: write 
  pull-requests: write 

jobs:
  merge_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v3

    - name: Check if PR is Approved
      run: |
        # Fetch the reviews for the PR
        review_state=$(curl -s \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews)
        
        # Check if any review is approved using grep
        if echo "$review_state" | grep -q '"state": "APPROVED"'; then
          echo "PR is approved, merging now."
        else
          echo "PR is not approved yet, skipping merge."
          exit 1
        fi

    - name: Merge Pull Request
      if: success()  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X PUT \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge \
          -d '{"merge_method":"merge"}'